 const flightList = [
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 500,
      duration: 5,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1300,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 200,
      duration: 2,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1500,
      duration: 10,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1334,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 900,
      duration: 3,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 12000,
      duration: 10,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 6000,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1800,
      duration: 3,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 90000,
      duration: 20,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1400,
      duration: 4,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 6600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 45000,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 9600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 500,
      duration: 5,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1300,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 200,
      duration: 2,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1500,
      duration: 10,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1334,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 900,
      duration: 3,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 12000,
      duration: 10,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 6000,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1800,
      duration: 3,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 90000,
      duration: 20,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 1400,
      duration: 4,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 6600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 45000,
      duration: 6,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
    {
      // dapartureCity: "AAA",
      // arrivalCity: "AAE",
      // tripWay: "onewaytrip",
      // journeyDate: "2023-10-25",
      // returnDate: "2023-10-25",
      // adults: 2,
      // childs: 0,
      // class: "Economy",
      // currency: "USD",
      price: 9600,
      duration: 7,
      stopage: "Non stop",
      airline: "Biman Bangladesh",
    },
   
  ];
  module.exports = flightList


