const hotelList = [
    {
        name: "Ocean Paradise",
        starCount: 4,
        price: 1334,
        discount: "10%",
        image: "img.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Luxury Suites",
        starCount: 5,
        price: 2200,
        discount: "15%",
        image: "luxury.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Cozy Inn",
        starCount: 3,
        price: 850,
        discount: "5%",
        image: "cozy.png",
        AC: false,
        breakfast: false,
    },
    {
        name: "Seaside Villa",
        starCount: 4,
        price: 1650,
        discount: "12%",
        image: "seaside.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Mountain View Lodge",
        starCount: 3,
        price: 1200,
        discount: "8%",
        image: "mountain.png",
        AC: true,
        breakfast: false,
    },
    {
        name: "Riverside Retreat",
        starCount: 4,
        price: 1450,
        discount: "10%",
        image: "riverside.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Cityscape Hotel",
        starCount: 4,
        price: 1550,
        discount: "9%",
        image: "cityscape.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Desert Oasis Resort",
        starCount: 5,
        price: 1900,
        discount: "14%",
        image: "desert.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Historic Inn",
        starCount: 3,
        price: 950,
        discount: "6%",
        image: "historic.png",
        AC: false,
        breakfast: true,
    },
    {
        name: "Green Valley Lodge",
        starCount: 4,
        price: 1400,
        discount: "10%",
        image: "greenvalley.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Tropical Paradise Resort",
        starCount: 5,
        price: 2500,
        discount: "20%",
        image: "tropical.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Hilltop Hideaway",
        starCount: 4,
        price: 1750,
        discount: "11%",
        image: "hilltop.png",
        AC: true,
        breakfast: false,
    },
    {
        name: "Charming Cottage",
        starCount: 3,
        price: 1100,
        discount: "7%",
        image: "cottage.png",
        AC: false,
        breakfast: true,
    },
    {
        name: "Lakeside Lodge",
        starCount: 4,
        price: 1600,
        discount: "9%",
        image: "lakeside.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Urban Retreat Hotel",
        starCount: 4,
        price: 1750,
        discount: "10%",
        image: "urban.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Snowy Mountain Chalet",
        starCount: 4,
        price: 1850,
        discount: "12%",
        image: "chalet.png",
        AC: true,
        breakfast: false,
    },
    {
        name: "Ocean Paradise",
        starCount: 4,
        price: 1334,
        discount: "10%",
        image: "img.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Luxury Suites",
        starCount: 5,
        price: 2200,
        discount: "15%",
        image: "luxury.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Cozy Inn",
        starCount: 3,
        price: 850,
        discount: "5%",
        image: "cozy.png",
        AC: false,
        breakfast: false,
    },
    {
        name: "Seaside Villa",
        starCount: 4,
        price: 1650,
        discount: "12%",
        image: "seaside.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Mountain View Lodge",
        starCount: 3,
        price: 1200,
        discount: "8%",
        image: "mountain.png",
        AC: true,
        breakfast: false,
    },
    {
        name: "Riverside Retreat",
        starCount: 4,
        price: 1450,
        discount: "10%",
        image: "riverside.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Cityscape Hotel",
        starCount: 4,
        price: 1550,
        discount: "9%",
        image: "cityscape.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Desert Oasis Resort",
        starCount: 5,
        price: 1900,
        discount: "14%",
        image: "desert.png",
        AC: true,
        breakfast: true,
    },
    {
        name: "Historic Inn",
        starCount: 3,
        price: 950,
        discount: "6%",
        image: "historic.png",
        AC: false,
        breakfast: true,
    },
    {
        name: "Green Valley Lodge",
        starCount: 4,
        price: 1400,
        discount: "10%",
        image: "greenvalley.png",
        AC: true,
        breakfast: true,
    },
];


module.exports = hotelList;