const hotelList = [
  {
    name: "Ocean Paradise",
    starCount: 4,
    price: 1334,
    discount: "10%",
    image: "img.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 4.4,
    available: 2,
  },
  {
    name: "Luxury Suites",
    starCount: 5,
    price: 2200,
    discount: "15%",
    image: "luxury.png",
    AC: true,
    breakfast: true,
    status: "Popular",
    rating: 2.4,
    available: 7,
  },
  {
    name: "Cozy Inn",
    starCount: 3,
    price: 850,
    discount: "5%",
    image: "cozy.png",
    AC: false,
    breakfast: false,
    status: "Top Selling",
    rating: 3.0,
    available: 4,
  },
  {
    name: "Seaside Villa",
    starCount: 4,
    price: 1650,
    discount: "12%",
    image: "seaside.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 3.9,
    available: 8,
  },
  {
    name: "Mountain View Lodge",
    starCount: 3,
    price: 1200,
    discount: "8%",
    image: "mountain.png",
    AC: true,
    breakfast: false,
    status: "Popular",
    rating: 4.2,
    available: 7,
  },
  {
    name: "Riverside Retreat",
    starCount: 4,
    price: 1450,
    discount: "10%",
    image: "riverside.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 4.8,
    available: 12,
  },
  {
    name: "Cityscape Hotel",
    starCount: 4,
    price: 1550,
    discount: "9%",
    image: "cityscape.png",
    AC: true,
    breakfast: true,
    status: "Popular",
    rating: 3.1,
    available: 1,
  },
  {
    name: "Desert Oasis Resort",
    starCount: 5,
    price: 1900,
    discount: "14%",
    image: "desert.png",
    AC: true,
    breakfast: true,
    status: "Top Selling",
    rating: 3.2,
    available: 3,
  },
  {
    name: "Historic Inn",
    starCount: 3,
    price: 950,
    discount: "6%",
    image: "historic.png",
    AC: false,
    breakfast: true,
    status: "Trending",
    rating: 3.3,
    available: 2,
  },
  {
    name: "Green Valley Lodge",
    starCount: 4,
    price: 1400,
    discount: "10%",
    image: "greenvalley.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 3.4,
    available: 10,
  },
  {
    name: "Tropical Paradise Resort",
    starCount: 5,
    price: 2500,
    discount: "20%",
    image: "tropical.png",
    AC: true,
    breakfast: true,
    status: "Top Selling",
    rating: 4.9,
    available: 1,
  },
  {
    name: "Hilltop Hideaway",
    starCount: 4,
    price: 1750,
    discount: "11%",
    image: "hilltop.png",
    AC: true,
    breakfast: false,
    status: "Popular",
    rating: 2.9,
    available: 3,
  },
  {
    name: "Charming Cottage",
    starCount: 3,
    price: 1100,
    discount: "7%",
    image: "cottage.png",
    AC: false,
    breakfast: true,
    status: "Popular",
    rating: 3.7,
    available: 7,
  },
  {
    name: "Lakeside Lodge",
    starCount: 4,
    price: 1600,
    discount: "9%",
    image: "lakeside.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 3.8,
    available: 4,
  },
  {
    name: "Urban Retreat Hotel",
    starCount: 4,
    price: 1750,
    discount: "10%",
    image: "urban.png",
    AC: true,
    breakfast: true,
    status: "Top Selling",
    rating: 3.0,
    available: 2,
  },
  {
    name: "Snowy Mountain Chalet",
    starCount: 4,
    price: 1850,
    discount: "12%",
    image: "chalet.png",
    AC: true,
    breakfast: false,
    status: "Trending",
    rating: 3.0,
    available: 6,
  },
  {
    name: "Ocean Paradise",
    starCount: 4,
    price: 1334,
    discount: "10%",
    image: "img.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 3.0,
    available: 9,
  },
  {
    name: "Luxury Suites",
    starCount: 5,
    price: 2200,
    discount: "15%",
    image: "luxury.png",
    AC: true,
    breakfast: true,
    status: "Popular",
    rating: 3.9,
    available: 8,
  },
  {
    name: "Cozy Inn",
    starCount: 3,
    price: 850,
    discount: "5%",
    image: "cozy.png",
    AC: false,
    breakfast: false,
    status: "Trending",
    rating: 2.9,
    available: 3,
  },
  {
    name: "Seaside Villa",
    starCount: 4,
    price: 1650,
    discount: "12%",
    image: "seaside.png",
    AC: true,
    breakfast: true,
    status: "Top Selling",
    rating: 4.4,
    available: 11,
  },
  {
    name: "Mountain View Lodge",
    starCount: 3,
    price: 1200,
    discount: "8%",
    image: "mountain.png",
    AC: true,
    breakfast: false,
    status: "Trending",
    rating: 4.8,
    available: 10,
  },
  {
    name: "Riverside Retreat",
    starCount: 4,
    price: 1450,
    discount: "10%",
    image: "riverside.png",
    AC: true,
    breakfast: true,
    status: "Popular",
    rating: 3.4,
    available: 9,
  },
  {
    name: "Cityscape Hotel",
    starCount: 4,
    price: 1550,
    discount: "9%",
    image: "cityscape.png",
    AC: true,
    breakfast: true,
    status: "Top Selling",
    rating: 3.5,
    available: 7,
  },
  {
    name: "Desert Oasis Resort",
    starCount: 5,
    price: 1900,
    discount: "14%",
    image: "desert.png",
    AC: true,
    breakfast: true,
    status: "Popular",
    rating: 3.0,
    available: 1,
  },
  {
    name: "Historic Inn",
    starCount: 3,
    price: 950,
    discount: "6%",
    image: "historic.png",
    AC: false,
    breakfast: true,
    status: "Top Selling",
    rating: 3.4,
    available: 2,
  },
  {
    name: "Green Valley Lodge",
    starCount: 4,
    price: 1400,
    discount: "10%",
    image: "greenvalley.png",
    AC: true,
    breakfast: true,
    status: "Trending",
    rating: 3.0,
    available: 6,
  },
];

module.exports = hotelList;
